# Generated by Django 4.2.4 on 2023-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_address_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
