# Generated by Django 3.0.5 on 2023-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0004_auto_20230810_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_threshold', models.PositiveIntegerField(default=10000)),
            ],
        ),
    ]
