# Generated by Django 3.0.5 on 2023-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='standard_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
