# Generated by Django 3.0.5 on 2023-08-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0006_siteconfiguration_standard_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='standard_shipping_cost',
            new_name='shipping_cost',
        ),
    ]
