# Generated by Django 3.0.5 on 2023-08-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0007_auto_20230810_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
