# Generated by Django 3.0.5 on 2023-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_variation'),
        ('greatkart', '0008_cartitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='sales.Variation'),
        ),
    ]
