# Generated by Django 4.2.4 on 2023-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_variation_product_variations'),
        ('greatkart', '0011_remove_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='sales.variation'),
        ),
    ]
