# Generated by Django 4.2.4 on 2023-08-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0012_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
