# Generated by Django 4.2.4 on 2023-08-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0013_rename_variations_cartitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
    ]
