# Generated by Django 4.2.4 on 2023-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0014_remove_cartitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tax_amount_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
