# Generated by Django 4.2.4 on 2023-08-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greatkart', '0019_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
