# Generated by Django 4.2.4 on 2023-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
