# Generated by Django 4.2.4 on 2023-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_category_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
