# Generated by Django 4.2.4 on 2023-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_category_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_order',
        ),
    ]
