# Generated by Django 4.2.4 on 2023-08-09 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_category_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
