# Generated by Django 4.2.4 on 2023-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_specification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_1_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_2_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_3_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_point_1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_point_2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_point_3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
