# Generated by Django 4.2.4 on 2023-08-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bullet_1_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullet_2_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullet_3_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullet_point_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullet_point_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bullet_point_3',
        ),
    ]
