# Generated by Django 4.2.4 on 2023-08-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_brand_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
